import Head from "next/head";

//FIXEME: change name by project
const APP_NAME = "BoilerPlate";

type props = {
	title: string;
};

export function Seo({ title }: props) {
	return (
		<Head>
			<title>{`${APP_NAME} | ${title}`}</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/42_icon.png" />
		</Head>
	);
}
